services:
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - ./dados_banco:/var/lib/mysql